name: Daily ETL (Stormglass → history.csv → site/data.json)

on:
  schedule:
    # 07:00 UTC = 14:00 Asia/Ho_Chi_Minh
    - cron: "0 7 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r etl/requirements.txt

      - name: Run ETL
        env:
          STORMGLASS_KEY: ${{ secrets.STORMGLASS_KEY }}
        run: |
          python etl/fetch_and_merge.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add data/history.csv site/data.json
            git commit -m "ETL: update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes"
          fi
